version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: components/
    schedule:
      interval: weekly
    groups:
      minorAndPatch:
        update-types:
          - "minor"
          - "patch"