export const LAPIS_URL = 'https://lapis.cov-spectrum.org/open/v2';

export const AGGREGATED_ENDPOINT = `${LAPIS_URL}/sample/aggregated`;
export const NUCLEOTIDE_MUTATIONS_ENDPOINT = `${LAPIS_URL}/sample/nucleotideMutations`;
export const AMINO_ACID_MUTATIONS_ENDPOINT = `${LAPIS_URL}/sample/aminoAcidMutations`;
export const NUCLEOTIDE_INSERTIONS_ENDPOINT = `${LAPIS_URL}/sample/nucleotideInsertions`;
export const REFERENCE_GENOME_ENDPOINT = `${LAPIS_URL}/sample/referenceGenome`;

// WISE Wastewater
// This is a special instance for storing Swiss wastewater data generated by the WISE consortium
export const WISE_LAPIS_URL = 'https://api.wise-loculus.genspectrum.org/rsv';
export const WISE_DETAILS_ENDPOINT = `${WISE_LAPIS_URL}/sample/details`;
export const WISE_REFERENCE_GENOME_ENDPOINT = `${WISE_LAPIS_URL}/sample/referenceGenome`;
