export const visualizationStories = [
    {
        id: 'visualization-prevalence-over-time--two-datasets',
        title: 'Prevalence over time',
        loadingIsDoneIndicator: 'Bubble',
        testDownloadWithFilename: 'prevalence_over_time.csv',
    },
    {
        id: 'visualization-prevalence-over-time--one-dataset',
        title: 'Prevalence over time',
        loadingIsDoneIndicator: 'Bubble',
    },
    {
        id: 'visualization-prevalence-over-time--one-dataset-on-line-tab',
        title: 'Prevalence over time',
        loadingIsDoneIndicator: 'Bubble',
    },
    {
        id: 'visualization-prevalence-over-time--one-dataset-on-bubble-tab',
        title: 'Prevalence over time',
        loadingIsDoneIndicator: 'Bubble',
    },
    {
        id: 'visualization-prevalence-over-time--one-dataset-on-table-tab',
        title: 'Prevalence over time',
        loadingIsDoneIndicator: 'Bubble',
    },
    {
        id: 'visualization-prevalence-over-time--with-fixed-height',
        title: 'Prevalence over time',
        loadingIsDoneIndicator: 'Bar',
    },
    {
        id: 'visualization-relative-growth-advantage--default',
        title: 'Relative growth advantage',
        loadingIsDoneIndicator: 'Relative advantage:',
    },
    {
        id: 'visualization-relative-growth-advantage--with-fixed-height',
        title: 'Relative growth advantage',
        loadingIsDoneIndicator: 'Relative advantage:',
    },
    {
        id: 'visualization-mutations--default',
        title: 'Mutations',
        loadingIsDoneIndicator: 'Insertions',
        testDownloadWithFilename: 'substitutions_and_deletions.csv',
    },
    {
        id: 'visualization-mutations--on-table-tab',
        title: 'Mutations',
        loadingIsDoneIndicator: 'Insertions',
    },
    {
        id: 'visualization-mutations--on-table-tab-without-jaccard-similarity',
        title: 'Mutations',
        loadingIsDoneIndicator: 'Insertions',
        testDownloadWithFilename: 'substitutions_and_deletions.csv',
    },
    {
        id: 'visualization-mutations--on-insertions-tab',
        title: 'Mutations',
        loadingIsDoneIndicator: 'ins_1813:A',
        testDownloadWithFilename: 'insertions.csv',
    },
    {
        id: 'visualization-mutations--with-fixed-height',
        title: 'Mutations',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-mutation-comparison--default',
        title: 'Mutation comparison',
        loadingIsDoneIndicator: 'Table',
        testDownloadWithFilename: 'mutation_comparison.csv',
    },
    {
        id: 'visualization-mutation-comparison--venn-diagram',
        title: 'Mutation comparison',
        loadingIsDoneIndicator: 'Table',
    },
    {
        id: 'visualization-mutation-comparison--with-fixed-height',
        title: 'Mutation comparison',
        loadingIsDoneIndicator: 'Table',
    },
    {
        id: 'visualization-aggregate--default',
        title: 'Aggregate',
        testDownloadWithFilename: 'aggregate.csv',
        loadingIsDoneIndicator: 'Table',
    },
    {
        id: 'visualization-aggregate--with-fixed-height',
        title: 'Aggregate',
        loadingIsDoneIndicator: 'Table',
    },
    {
        id: 'visualization-aggregate--bar-chart-with-one-field',
        title: 'Aggregate',
        loadingIsDoneIndicator: 'Bar',
    },
    {
        id: 'visualization-aggregate--bar-chart-with-two-fields',
        title: 'Aggregate',
        loadingIsDoneIndicator: 'Bar',
    },
    {
        id: 'visualization-number-sequences-over-time--one-dataset-bar-chart',
        title: 'Number of sequences over time',
        loadingIsDoneIndicator: 'Bar',
    },
    {
        id: 'visualization-number-sequences-over-time--one-dataset-line-chart',
        title: 'Number of sequences over time',
        loadingIsDoneIndicator: 'Bar',
    },
    {
        id: 'visualization-number-sequences-over-time--one-dataset-table',
        title: 'Number of sequences over time',
        loadingIsDoneIndicator: 'Bar',
    },
    {
        id: 'visualization-number-sequences-over-time--two-datasets',
        title: 'Number of sequences over time',
        loadingIsDoneIndicator: 'Bar',
        testDownloadWithFilename: 'number_of_sequences_over_time.csv',
    },
    {
        id: 'visualization-number-sequences-over-time--two-datasets-with-non-overlapping-dates',
        title: 'Number of sequences over time',
        loadingIsDoneIndicator: 'Bar',
    },
    {
        id: 'visualization-number-sequences-over-time--with-fixed-height',
        title: 'Number of sequences over time',
        loadingIsDoneIndicator: 'Bar',
    },
    {
        id: 'visualization-mutations-over-time--by-month',
        title: 'Mutations over time',
        loadingIsDoneIndicator: 'Grid',
        testDownloadWithFilename: 'mutations_over_time.csv',
    },
    {
        id: 'visualization-mutations-over-time--by-month-with-filter-on-displayed-mutations',
        title: 'Mutations over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-mutations-over-time--by-month-with-filter-on-displayed-mutations-and-gaps',
        title: 'Mutations over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-mutations-over-time--by-week',
        title: 'Mutations over time',
        loadingIsDoneIndicator: 'Grid',
        testDownloadWithFilename: 'mutations_over_time.csv',
    },
    {
        id: 'visualization-mutations-over-time--amino-acid-mutations-by-day',
        title: 'Mutations over time',
        loadingIsDoneIndicator: 'Grid',
        testDownloadWithFilename: 'mutations_over_time.csv',
    },
    {
        id: 'visualization-mutations-over-time--hide-proportion-on-small-screen',
        title: 'Mutations over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-mutations-over-time--with-fixed-height',
        title: 'Mutations over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-mutations-over-time--with-custom-columns',
        title: 'Mutations over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-queries-over-time--default',
        title: 'Queries over time',
        loadingIsDoneIndicator: 'Grid',
        testDownloadWithFilename: 'queries_over_time.csv',
    },
    {
        id: 'visualization-queries-over-time--with-fixed-height',
        title: 'Queries over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-queries-over-time--by-week',
        title: 'Queries over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-queries-over-time--with-custom-columns',
        title: 'Queries over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-queries-over-time--hide-gaps',
        title: 'Queries over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-queries-over-time--small-width',
        title: 'Queries over time',
        loadingIsDoneIndicator: 'Grid',
    },
    {
        id: 'visualization-statistics--default',
        title: 'Statistics',
        loadingIsDoneIndicator: 'Sequences',
    },
    {
        id: 'visualization-sequences-by-location--world-map',
        title: 'Sequences by location',
        loadingIsDoneIndicator: 'Leaflet',
    },
    {
        id: 'visualization-sequences-by-location--germany',
        title: 'Sequences by location',
        loadingIsDoneIndicator: 'Leaflet',
        testDownloadWithFilename: 'sequences_by_location.csv',
    },
    {
        id: 'visualization-sequences-by-location--germany-on-table-tab',
        title: 'Sequences by location',
        loadingIsDoneIndicator: 'Bavaria',
    },
    {
        id: 'visualization-sequences-by-location--germany-table-only',
        title: 'Sequences by location',
        loadingIsDoneIndicator: 'Bavaria',
        testDownloadWithFilename: 'sequences_by_location.csv',
    },
    {
        id: 'visualization-sequences-by-location--with-fixed-height',
        title: 'Sequences by location',
        loadingIsDoneIndicator: 'Leaflet',
    },
    {
        id: 'wastewater-visualization-wastewater-mutations-over-time--wastewater-mutations-over-time',
        title: 'Wastewater Mutations Over Time',
        loadingIsDoneIndicator: 'Lugano',
    },
    {
        id: 'visualization-genome-data-viewer--default',
        title: 'Genome Data Viewer',
        loadingIsDoneIndicator: 'NS1',
    },
];
